<?php
if (!defined('ABSPATH')) exit;
class TAPT_DB {
 public static function tables(){ global $wpdb; return ['lotteries'=>$wpdb->prefix.'tapt_lotteries','modalities'=>$wpdb->prefix.'tapt_modalities','draws'=>$wpdb->prefix.'tapt_draws','results'=>$wpdb->prefix.'tapt_results','imports'=>$wpdb->prefix.'tapt_imports','log'=>$wpdb->prefix.'tapt_activity_log']; }
 public static function activate(){ global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::tables(); $c=$wpdb->get_charset_collate();
  dbDelta("CREATE TABLE {$t['lotteries']} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,name VARCHAR(120) NOT NULL,slug VARCHAR(80) NOT NULL,game_type VARCHAR(40) NOT NULL DEFAULT 'number_draw',number_min SMALLINT NOT NULL DEFAULT 0,number_max SMALLINT NOT NULL DEFAULT 45,numbers_drawn SMALLINT NOT NULL DEFAULT 6,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY slug(slug)) $c;");
  dbDelta("CREATE TABLE {$t['modalities']} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,lottery_id BIGINT UNSIGNED NOT NULL,code VARCHAR(20) NOT NULL,name VARCHAR(120) NOT NULL,color VARCHAR(20) DEFAULT '#2563eb',sort_order SMALLINT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,PRIMARY KEY(id),UNIQUE KEY lottery_code(lottery_id,code),KEY lottery_id(lottery_id)) $c;");
  dbDelta("CREATE TABLE {$t['draws']} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,lottery_id BIGINT UNSIGNED NOT NULL,contest_number VARCHAR(40) NOT NULL,draw_date DATE NOT NULL,draw_time TIME NULL,source_note VARCHAR(255) NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY lottery_contest(lottery_id,contest_number),KEY draw_date(draw_date)) $c;");
  dbDelta("CREATE TABLE {$t['results']} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,draw_id BIGINT UNSIGNED NOT NULL,modality_id BIGINT UNSIGNED NOT NULL,number_value SMALLINT NOT NULL,position SMALLINT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY result_unique(draw_id,modality_id,number_value),KEY modality_number(modality_id,number_value),KEY draw_modality(draw_id,modality_id)) $c;");
  dbDelta("CREATE TABLE {$t['imports']} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,filename VARCHAR(255) NOT NULL,lottery_id BIGINT UNSIGNED NOT NULL,total_rows INT NOT NULL DEFAULT 0,inserted_rows INT NOT NULL DEFAULT 0,duplicates INT NOT NULL DEFAULT 0,conflicts INT NOT NULL DEFAULT 0,errors INT NOT NULL DEFAULT 0,user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id)) $c;");
  dbDelta("CREATE TABLE {$t['log']} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,action VARCHAR(40) NOT NULL,entity_type VARCHAR(40) NOT NULL,entity_id BIGINT UNSIGNED NULL,details LONGTEXT NULL,user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),KEY action(action)) $c;");
  update_option('tapt_db_version',TAPT_DB_VERSION); self::seed_quini6(); }
 public static function seed_quini6(){ global $wpdb; $t=self::tables(); $id=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t['lotteries']} WHERE slug=%s",'quini6')); if(!$id){$wpdb->insert($t['lotteries'],['name'=>'Quini 6','slug'=>'quini6','game_type'=>'number_draw','number_min'=>0,'number_max'=>45,'numbers_drawn'=>6,'is_active'=>1,'created_at'=>current_time('mysql')]);$id=$wpdb->insert_id;} foreach([['1','Tradicional','#2563eb',1],['2','La Segunda','#16a34a',2],['3','Revancha','#dc2626',3],['4','Siempre Sale','#9333ea',4]] as $m){$wpdb->query($wpdb->prepare("INSERT IGNORE INTO {$t['modalities']} (lottery_id,code,name,color,sort_order,is_active) VALUES (%d,%s,%s,%s,%d,1)",$id,$m[0],$m[1],$m[2],$m[3]));}}
 public static function lotteries(){global $wpdb;$t=self::tables();return $wpdb->get_results("SELECT * FROM {$t['lotteries']} WHERE is_active=1 ORDER BY name");}
 public static function modalities($lottery_id){global $wpdb;$t=self::tables();return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$t['modalities']} WHERE lottery_id=%d AND is_active=1 ORDER BY sort_order,name",$lottery_id));}
 public static function log($action,$type,$id=null,$details=[]){global $wpdb;$t=self::tables();$wpdb->insert($t['log'],['action'=>$action,'entity_type'=>$type,'entity_id'=>$id,'details'=>wp_json_encode($details),'user_id'=>get_current_user_id(),'created_at'=>current_time('mysql')]);}
}
